version: '3.7'

services:
  db-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_MULTIPLE_DATABASES: objective7p,functional8p,reactive8pr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgreSS!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:4.2.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./db_init/mongo:/docker-entrypoint-initdb.d
      - mongodb-data:/data/db/

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "81:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin-password

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"

volumes:
  postgres-data:
  mongodb-data: